import type { Vulnerability } from './types'

export const vulnerabilities: Vulnerability[] = [
  {
    id: 'v1',
    cve: 'CVE-2024-6387',
    service: 'OpenSSH 8.9p1',
    asset: '10.0.0.12 (web-prod-01)',
    severity: 'critical',
    cvss: 8.1,
    exploitAvailable: true,
    evidence: 'Banner grab confirmó versión vulnerable de OpenSSH en el puerto 22.',
    source: 'NVD / Searchsploit',
    recommendation: 'Actualizar OpenSSH a la versión 9.8 o superior lo antes posible.',
    status: 'open',
  },
  {
    id: 'v2',
    cve: 'CVE-2023-44487',
    service: 'HTTP/2 (nginx)',
    asset: '10.0.0.12 (web-prod-01)',
    severity: 'high',
    cvss: 7.5,
    exploitAvailable: true,
    evidence: 'Servidor responde a peticiones HTTP/2 con soporte de stream reset.',
    source: 'NVD',
    recommendation: 'Aplicar mitigación de rate-limiting y actualizar nginx.',
    status: 'in_progress',
  },
  {
    id: 'v3',
    cve: 'CVE-2022-1292',
    service: 'OpenSSL 1.1.1',
    asset: '10.0.0.15 (db-prod-01)',
    severity: 'high',
    cvss: 9.8,
    exploitAvailable: false,
    evidence: 'Versión de OpenSSL detectada en handshake TLS del servicio PostgreSQL.',
    source: 'NVD',
    recommendation: 'Actualizar OpenSSL a la versión 3.0.3 o parche equivalente.',
    status: 'open',
  },
  {
    id: 'v4',
    cve: 'CVE-2021-41773',
    service: 'Apache HTTP Server',
    asset: '10.0.0.33 (legacy-app-01)',
    severity: 'medium',
    cvss: 5.3,
    exploitAvailable: false,
    evidence: 'Path traversal potencial detectado en configuración de Apache 2.4.49.',
    source: 'Searchsploit',
    recommendation: 'Actualizar Apache o restringir acceso a directorios sensibles.',
    status: 'accepted_risk',
  },
  {
    id: 'v5',
    cve: 'CVE-2020-15778',
    service: 'OpenSSH SCP',
    asset: '10.0.0.20 (mail-01)',
    severity: 'low',
    cvss: 3.5,
    exploitAvailable: false,
    evidence: 'Posible inyección de comandos vía SCP en configuración por defecto.',
    source: 'NVD',
    recommendation: 'Migrar de SCP a SFTP para transferencias de archivos.',
    status: 'resolved',
  },
]